image: docker
services:
  - docker:dind

variables:
  CI_REGISTRY_USER: matej0506
  CI_REGISTRY: docker.io
  CI_REGISTRY_IMAGE: index.docker.io/matej0506/five-node-test

before_script:
  - apk add --no-cache docker-compose
  - echo "$CI_REGISTRY_PASSWORD" | docker login --username "$CI_REGISTRY_USER" $CI_REGISTRY --password-stdin

after_script:
  - docker-compose down -v

test:
  script:
    - export TAG=${CI_COMMIT_SHORT_SHA}
    - docker-compose up --build -d
    - docker-compose exec -T nodejs npm test
    - docker push matej0506/five-node-test:${TAG}

deploy:
  stage: deploy
  when: manual
  variables:
    CI_AWS_ECS_CLUSTER: five-node-test
    CI_AWS_ECS_SERVICE: five-node-test
    CI_AWS_ECS_TASK_DEFINITION: five-node-test:1
  before_script: []
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-ecs:latest
  script:
    - aws ecs update-service --cluster ${CI_AWS_ECS_CLUSTER} --service ${CI_AWS_ECS_SERVICE} --task-definition ${CI_AWS_ECS_TASK_DEFINITION}
  after_script: []
