image: docker
services:
  - docker:dind

variables:
  CI_REGISTRY_USER: matej0506
  CI_REGISTRY: docker.io
  CI_REGISTRY_IMAGE: index.docker.io/matej0506/five-node-test

before_script:
  - apk add --no-cache docker-compose
  - echo "$CI_REGISTRY_PASSWORD" | docker login --username "$CI_REGISTRY_USER" $CI_REGISTRY --password-stdin

test:
  script:
    - export TAG=${CI_COMMIT_SHORT_SHA}
    - docker-compose up --build -d
    - docker-compose exec -T nodejs npm test
    - docker push matej0506/five-node-test:${TAG}

after_script:
  - docker-compose down -v

deploy:
  stage: deploy
  when: manual
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest  # see the note below
  script:
    - aws -h
